unit UConst;

{$mode ObjFPC}{$H+}

interface

uses
  Graphics, fpstypes;

const
  SCHEME_FONT_FILENAME     = 'JetBrains Mono Regular Nerd Font Complete.ttf';
  SCHEME_FONT_NAME_DEFAULT = 'JetBrainsMono Nerd Font';
  SCHEME_FONT_SIZE_DEFAULT = 14;

  TABLE_MAIN_LINE_STYLE = lsThin;

  TABLE_TITLE_FONT_SIZE = SCHEME_FONT_SIZE_DEFAULT-2;
  TABLE_TITLE_FONT_STYLE = [fsBold];

  TABLE_DESCRIPTION_FONT_SIZE = SCHEME_FONT_SIZE_DEFAULT-4;
  TABLE_DESCRIPTION_FONT_STYLE = [];

  TABLE_NOTES_FONT_SIZE = SCHEME_FONT_SIZE_DEFAULT-4;
  TABLE_NOTES_FONT_STYLE = [];

  FIELD_NAME_FONT_SIZE = SCHEME_FONT_SIZE_DEFAULT-6;
  FIELD_NAME_FONT_STYLE = [];

  FIELD_TYPE_FONT_SIZE = SCHEME_FONT_SIZE_DEFAULT-6;
  FIELD_TYPE_FONT_STYLE = [];

  FIELD_SYMBOLS_FONT_SIZE = SCHEME_FONT_SIZE_DEFAULT-3;
  FIELD_SYMBOLS_FONT_STYLE = [fsBold];

  FIELD_DEFVALUE_FONT_SIZE = SCHEME_FONT_SIZE_DEFAULT-6;
  FIELD_DEFVALUE_FONT_STYLE = [];

  FIELD_REFERENCE_FONT_SIZE = SCHEME_FONT_SIZE_DEFAULT-8;
  FIELD_REFERENCE_FONT_STYLE = [];

  FIELD_DESCRIPTION_FONT_SIZE = SCHEME_FONT_SIZE_DEFAULT-7;
  FIELD_DESCRIPTION_FONT_STYLE = [];

  COLOR_BACKGROUND = clWindow;
  COLOR_BACKGROUND_EXTRA      = $00D6E9D6;
  COLOR_TEXT = clWindowText;
  COLOR_TEXT_SELECTED = clBlack;
  COLOR_GRIDLINE = clWindowText;

  MIDDLE_ROW_HEIGHT = 15;

  SYMBOL_PRIMARYKEY = '';
  SYMBOL_AUTOINC = '﭅';
  SYMBOL_NULL = 'ﱤ';
  SYMBOL_NOTNULL = 'ﰸ';
  SYMBOL_UNIQUE = '';
  SYMBOL_REFERENCETO = '';
  SYMBOL_REFERENCEFROM = '';

implementation

end.

